### ISSUE TITLE
Formulate predictive research question

### ISSUE THREAD

**Issue by cgostic** [UBC-MDS/DSCI_522_group_415#1]
From lecture, here are some examples of predictive research questions:  
- How many viral illnesses will someone have next year?
- What political party will someone vote for in the next US election?
- What feature most strongly predict whether a tumour is malignant or benign?

Our dataset has only date and plate, so we'll have to create features to predict on... my initial thought was to take all 2-n letter combinations for a plate with n characters and use those as features (can do this with CountVectorizer) and then use use an NB classifier or other model.

e.g. if the plate = CATS, the features would be CA, AT, TS, CAT, ATS, CATS.

This would probably be a time intensive model, so let me know if you have any suggestions!

If you guys are into this, we could do something like the 3rd research question-- Which letter combinations most strongly predict a rejected license? And then a word map visualization for all the top features.

Any other brainstorms?

**Comment by Keanna-K** [comment]
Hey @cgostic,

Thanks for initializing our brainstorming process! I think the license plate data set is definitely best suited for a **predictive** research question. As our data is categorical, I think something similar to either the 2nd or 3rd research question would work best. 

I think your proposed question, "Which letter combinations most strongly predict a rejected license?" would be an interesting and fun idea to explore! Another idea, similar to the 2nd example question, we could try is "Will the vanity license _ _ _ _ be rejected?". Ex. would the vanity license 'KIKI4LYF3' be rejected?

**Comment by cgostic** [comment]
Keep in mind that we have to make a visualization... I think the second example would be fun, but I don't know how we'd present this in the report. For the third, we could do a word map. Any ideas on how we might visualize the second? If we can't think of something, I think the second is a better option for this project.

**Comment by Keanna-K** [comment]
Oh yes, I am not sure if we would be able to make an effective visualization for the second example... I think it would be best to go with "what are the best predictors for whether a license plate is rejected?". 
In addition to the word map, we could easily do some bar charts etc. to show the top predictors.

**Comment by fkhan72** [comment]
Sounds good. But isn't the question "what are the best predictors for whether a license plate is rejected?" leads to the question "Will the vanity license _ _ _ _ be rejected?" during the model prediction step. 

I think the first question can be answered using Nieve-Bayes model to evaluate the probability of each alphabet and letter for rejection? Then once the model is trained we can answer the second question during the prediction stage.

**Comment by fkhan72** [comment]
As far as the visuals are concerned, we dont want to change our research question based on the availability of visuals. In this project, we will have some validation visuals anyhow so it wont hurt to ask the question "Will the vanity license _ _ _ _ be rejected?" which is what to we see in many ML projects. Also, in this project, we have the support of the teaching staff to figure out the best ways to visualize the results.

**Comment by cgostic** [comment]
At the advice of the TA, we've decided on "what are the best predictors for whether a license plate is rejected?". We can always circle back and revise as the project progresses!
