### ISSUE TITLE
Script organization, and getting Script 2 products into scripts 3&4

### ISSUE THREAD

**Issue by cgostic** [UBC-MDS/DSCI_522_group_415#10]
Hi guys! I just spoke to Firas and since required scripts 1-5 will need to have command line arguments through docopt, we're gonna have to shift around the outputs of the Preprocess script Keanna made last night. 

- In script 2 (preprocess script), we will write the X/y_train, X/y_valid, and X/y_test datasets to a csv in the data folder. 
- We will create an extra script for functions (functions.py) and put a CountVectorizer function in there that fits on X_train, and returns X_train_trans, X_valid_trans, and X_test_trans.
- Script 3 and 4 will read in X/y_train/valid/test csvs from Script 2, and use the CountVecotrizer function to get X_train/valid/test_trans

This is because with docopt, the X_train/valid/test sets are created within the `main()` function and therefore cannot be accessed from other scripts. They need to be written to csv's to access from other scripts.

**Comment by fkhan72** [comment]
sounds good

**Comment by fkhan72** [comment]
I have developed a rough version of script 4. I have also implemented the CountVectorizer hyperparameter optimization for `analyzer` and `ngram_range` using pipeline and it seems to work well. But, in that case we dont need to use the already written CountVectorizer function. Are you guys ok with that?

**Comment by cgostic** [comment]
Yeah, that sounds good to me! I will still do my EDA on the maximum features we could have, and then that can feed into a quick discussion on optimization of ngram length in the report. 

So we don't need `function.py`? @fkhan72

**Comment by fkhan72** [comment]
Yes now, we dont need the function.py. I guess we can keep it for future use.
