### ISSUE TITLE
Download script issues

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/DSCI_522_group_415#13]
- Missing usage example to download your datasets
- Best practice is to have one script to download the datasets individually, then another one to combine them.
- Missing tests/assertions

**Comment by Keanna-K** [comment]
Thanks for the advice! As suggested we have split the download and combination of datasets into two separate scripts (script 01 downloads and script 02 processes the datasets). We have also added tests/assertions to our scripts. These updates were completed from pull request #12
