### ISSUE TITLE
Script flow Image

### ISSUE THREAD

**Issue by Keanna-K** [UBC-MDS/DSCI_522_group_415#17]
Not a big issue, just wanted to point out that our image of the script flow has one of the boxes selected (i.e. script 04 /img output is clicked on when the screenshot was taken). 
https://github.com/UBC-MDS/DSCI_522_group_415/blob/master/script_flowchart.png

**Comment by cgostic** [comment]
I'll fix it. I also think the images should by inputs into the rmd, not the html file. My bad!

**Comment by Keanna-K** [comment]
fixed with commit #21
