### ISSUE TITLE
Milestone 1 Preliminary Feedback

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/DSCI_522_group_415#8]
- Analysis plan looks good.
- Missing question type and sub-questions. Your dataset may limit the questions you can answer.
- Interesting choice of dataset and question, check with the lab instructor to see if it's suitable for the class. Even though I don't see a practical application, you might find interesting patterns in the approved plates.

**Comment by Keanna-K** [comment]
Thanks for the initial feedback.
We have specified the question type and added our sub-question.  #18 
We had already checked in lab week 1 to ensure our question was suitable for the class project and have specified the purpose and applications of our analysis in our report for milestone 2 as was required. #12
